export function ema(xs,n){let a=2/(n+1),v=xs[0]??0;return xs.map((x,i)=>v=i?x*a+v*(1-a):x)}
export function rma(xs,n){let v=xs[0]??0;return xs.map((x,i)=>v=i?(v*(n-1)+x)/n:x)}
export function indicators(bars){
 const c=bars.map(b=>b.close), e12=ema(c,12),e26=ema(c,26),dif=c.map((_,i)=>e12[i]-e26[i]),dea=ema(dif,9);
 let sumPV=0,sumV=0; return bars.map((b,i)=>{let tp=(b.high+b.low+b.close)/3;sumPV+=tp*b.volume;sumV+=b.volume;let tr=Math.max(b.high-b.low,i?Math.abs(b.high-c[i-1]):0,i?Math.abs(b.low-c[i-1]):0);return {...b,vwap:sumV?sumPV/sumV:null,difbps:c[i]?10000*dif[i]/c[i]:0,histbps:c[i]?20000*(dif[i]-dea[i])/c[i]:0,tr}}).map((b,i,a)=>({...b,atr5:rma(a.map(x=>x.tr),14)[i]}));
}
export function confirmedPivots(bars,cfg,asOf=bars.length-1){let lows=[],highs=[];for(let i=cfg.pivot_left;i+cfg.pivot_right<=asOf;i++){let w=bars.slice(i-cfg.pivot_left,i+cfg.pivot_right+1);if(bars[i].low<=Math.min(...w.map(x=>x.low)))lows.push({...bars[i],index:i,confirmedAt:i+cfg.pivot_right});if(bars[i].high>=Math.max(...w.map(x=>x.high)))highs.push({...bars[i],index:i,confirmedAt:i+cfg.pivot_right});}return {lows,highs}}
export function divergence(points,type,cfg){if(points.length<2)return null;let [a,b]=points.slice(-2),gap=b.index-a.index;if(gap<cfg.pivot_min_gap_bars||gap>cfg.pivot_max_gap_bars)return null;let bottom=type==='bottom',price=bottom?b.low<=a.low*(1+cfg.near_equal_price_tolerance):b.high>=a.high*(1-cfg.near_equal_price_tolerance),improve=bottom?b.difbps-a.difbps:a.difbps-b.difbps,need=Math.max(cfg.macd_min_improvement_bps,.15*Math.abs(a.difbps));if(!price||improve<need)return null;return {type,standard:bottom?b.low<a.low:b.high>a.high,volumeContracted:b.volume<=cfg.volume_contraction_ratio*a.volume,first:a,second:b}}
export function validateBars(bars){for(let i=0;i<bars.length;i++){if(!bars[i].time||bars[i].volume<=0)return {ok:false,reason:'缺失时间或零成交量'};if(i&&bars[i].time<=bars[i-1].time)return {ok:false,reason:'重复或乱序bar'};}return {ok:true}}
export function roundTripCost(c){return c.buy_commission+c.sell_commission+c.sell_taxes+2*c.slippage_rate}
export function tradeGate({direction,entry,stop,target,atr20,prevClose,score,cfg}){let gross=direction==='forward'?(target-entry)/entry:(entry-target)/entry, risk=direction==='forward'?entry-stop:stop-entry, reward=direction==='forward'?target-entry:entry-target,rr=risk>0?reward/risk:-Infinity,cost=roundTripCost(cfg),minGross=Math.max(.008,4*cost,.35*atr20/prevClose);let failures=[];if(rr<cfg.min_rr)failures.push('RR不足');if(gross<minGross)failures.push('毛价差不足');if(gross-cost<=0)failures.push('成本后净价差不足');if(score<cfg.min_score)failures.push('评分不足');return {pass:!failures.length,rr,gross,net:gross-cost,minGross,failures}}
export function suggestedQty({availableOldQty,cashAvailable,accountEquity,entry,stop,cfg}){if([availableOldQty,cashAvailable,accountEquity].some(x=>!Number.isFinite(x)))return {qty:null,reason:'数量不可计算/不可执行'};let q=Math.min(availableOldQty*cfg.max_t_fraction,cashAvailable/entry,accountEquity*cfg.risk_per_trade/Math.abs(entry-stop));return {qty:Math.floor(q/cfg.lot_size)*cfg.lot_size}}
export class Replay {constructor(bars){this.bars=bars;this.cursor=0} next(){if(this.cursor>=this.bars.length)return null;return this.bars.slice(0,++this.cursor)} get future(){return undefined}}
export class DailyState {constructor(){this.days={}} open(symbol,date,direction,time,cfg){let k=`${date}:${symbol}`,s=this.days[k];if(s?.done||s?.direction)return false;if(time<cfg.no_new_cycle_before||time>cfg.no_new_cycle_after)return false;this.days[k]={direction,state:direction==='forward'?'FORWARD_OPEN':'REVERSE_OPEN'};return true}restore(symbol,date){let s=this.days[`${date}:${symbol}`];if(s)s.state='DONE'} serialize(){return JSON.stringify(this.days)} static from(x){let s=new DailyState;s.days=JSON.parse(x||'{}');return s}}
